### ISSUE TITLE
Support for Arch Linux packages?

### ISSUE THREAD

**Issue by dzhu** [goreleaser/nfpm#133]
Would there be any interest in adding support for [Arch Linux](https://www.archlinux.org) packages? I _may_ be able to provide this myself (no promises), so, even though I'm guessing it won't be a high priority, it would be good to know whether the answer is "yes, if there is a PR" or "no, we wouldn't want that".

**Comment by caarlos0** [comment]
check https://github.com/goreleaser/nfpm/pull/126

closing as duplicated

**Comment by dzhu** [comment]
Er, I don't think this is a duplicate: this is about Arch Linux, rather than Alpine Linux. Looks like there's a bit of [overlap](https://wiki.alpinelinux.org/wiki/Alpine_package_format#.PKGINFO) in the format of `.PKGINFO`, which I didn't know before, but otherwise they involve different formats.

**Comment by caarlos0** [comment]
sorry, totally misread :|

**Comment by dzhu** [comment]
No worries. :slightly_smiling_face: I'll look into doing this, then.

**Comment by olanod** [comment]
This would be awesome, any updates with the PR?

**Comment by caarlos0** [comment]
fwiw, goreleaser can now generate AUR PKGBUILD files and push to a remote, no packages directly, though.

https://goreleaser.com/customization/aur/
