### ISSUE TITLE
Add support for installinit

### ISSUE THREAD

**Issue by tonobo** [goreleaser/nfpm#15]
It would be nice if there where any possibilty to add service files. Debhelper installinit allows to specify several init files which will be automatically managed during install. (e.g enable on install or restart after upgrade). Probaply there is also an option to do the same for rpm.

**Comment by djmattyg007** [comment]
Please be careful about how this is implemented, if at all. The convention on Arch Linux systems is to NOT automatically start services at installation time.

**Comment by caarlos0** [comment]
This will likely not be implemented.

For tips on how to manage init files, check https://nfpm.goreleaser.com/tips/



> Please be careful about how this is implemented, if at all. The convention on Arch Linux systems is to NOT automatically start services at installation time.

we do not support arch just yet...
