### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/nfpm#229]
We have a lot of code that's not very well tested, either by unit or integration tests.

https://codecov.io/gh/goreleaser/nfpm

It would be nice to improve that a bit 🙏

**Comment by blueworrybear** [comment]
Hi @caarlos0!

I would like to contribute some test cases to increate the test coverage!

Please refer to [my commit](https://github.com/blueworrybear/nfpm/commit/15956c17c19efc159adbc3337b5c9f536fce8e3c) for the codes.

And here is the coverage report from [covergates](https://covergates.com/):

[![treemap](https://covergates.com/api/v1/reports/bu19l2a23akg00ckoqcg/treemap/?base=master&)](https://covergates.com/report/github/blueworrybear/nfpm?ref=15956c17c19efc159adbc3337b5c9f536fce8e3c)


### [Coverage: 80.1%](https://covergates.com/report/github/blueworrybear/nfpm?ref=15956c17c19efc159adbc3337b5c9f536fce8e3c)

||File|Coverage|
|--|--|--------|
||deb/deb.go|0.76|
||rpm/rpm.go|0.78|
||internal/sign/pgp.go|0.82|
|:arrow_up_small:|internal/sign/rsa.go|0.72|
||internal/glob/glob.go|0.94|
||nfpm.go|0.75|
||internal/files/files.go|0.83|
|:arrow_up_small:|apk/apk.go|0.80|

---

May I create a PR? Thank you and happy hacktoberfest!

**Comment by caarlos0** [comment]
Yes, thanks 🙏🙏

**Comment by erikgeiser** [comment]
Thanks for your contribution @blueworrybear. Sorry, but I don't really understand what the `sign.go` code is actually testing. `RSAVerifySHA1Digest` is actually not directly used by `nfpm` but exported to be used in tests in other packages. As far as I currently understand it, it is not really necessary to pull in all the dependencies to test different types of keys. I might be wrong, though.

**Comment by Dean-Coakley** [comment]
@caarlos0 Is this issue still relevant?

I just had a look at master and the coverage looks pretty solid to me.
```
ok  	github.com/goreleaser/nfpm/v2	4.114s	coverage: 85.9% of statements
ok  	github.com/goreleaser/nfpm/v2/apk	4.233s	coverage: 81.7% of statements
?   	github.com/goreleaser/nfpm/v2/cmd/nfpm	[no test files]
ok  	github.com/goreleaser/nfpm/v2/deb	4.557s	coverage: 78.2% of statements
ok  	github.com/goreleaser/nfpm/v2/files	2.752s	coverage: 83.3% of statements
ok  	github.com/goreleaser/nfpm/v2/internal/glob	2.590s	coverage: 91.4% of statements
ok  	github.com/goreleaser/nfpm/v2/internal/sign	4.409s	coverage: 84.7% of statements
ok  	github.com/goreleaser/nfpm/v2/rpm	4.846s	coverage: 81.2% of statements
```

Or do you want to keep this open for further imrprovement?

**Comment by caarlos0** [comment]
I think we can close it, thanks!
