### ISSUE TITLE
Use SHA256 or rename to SHA1

### ISSUE THREAD

**Issue by mterron** [goreleaser/nfpm#237]
https://github.com/goreleaser/nfpm/blob/3d7580ade2e01168e7a3487c145d44b98bc1eb3a/internal/sign/rsa.go#L67

This line is confusing, you talk about a SHA256 hash but are actually using SHA1.

**Comment by caarlos0** [comment]
cc/ @erikgeiser , I think it should indeed be sha1, am I correct?

**Comment by erikgeiser** [comment]
Yes of course. This is a leftover from when I tried to make APKs work with SHA256 for proper security. I must have missed this instance.
