### ISSUE TITLE
xi2 License Dependency

### ISSUE THREAD

**Issue by cliveseldon** [goreleaser/nfpm#242]
This project as xi2/xz as a dependency

https://github.com/goreleaser/nfpm/blob/a2ffae7a5dd9ad38ee4ed6fcb13bbf96fd9fd56d/go.mod#L20

However, that project has not used a standard license:

https://github.com/xi2/xz/blob/master/LICENSE

This is causing us problems with 3rd party open source dependency license validation. Is there any possibility of forking that library to republish it with a standard license? I have added an issue to their project https://github.com/xi2/xz/issues/10 but it seems inactive.

I also mentioned this on https://github.com/mholt/archiver/issues/259 which also uses this project.

**Comment by caarlos0** [comment]
> This is causing us problems with 3rd party open source dependency license validation. Is there any possibility of forking that library to republish it with a standard license?

I don't think thats a very cool thing to do. Maybe you can ignore it in your tooling?

Anyway, sorry, but will not do this.
