### ISSUE TITLE
bug: cannot download nfpm with go-releaser v1.10.1

### ISSUE THREAD

**Issue by tnhh00037** [goreleaser/nfpm#254]
On last version, I managed to download nfpm binary by using goreleaser script
`curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh`

The successful output: 
```sh
goreleaser/nfpm info checking GitHub for latest tag
goreleaser/nfpm info found version: 1.8.0 for v1.8.0/Linux/x86_64
goreleaser/nfpm info installed ./bin/nfpm
```

When there's new release `1.10.1` , I got this error ( even not modify nfpm.sh script)
```
> curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh
goreleaser/nfpm info checking GitHub for latest tag
goreleaser/nfpm info found version: 1.10.1 for v1.10.1/Linux/x86_64
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
( output doesn't have this line `goreleaser/nfpm info installed ./bin/nfpm` )
After modify VERSION. TAG variable inside above script to this
```
VERSION=1.8.0
TAG=v1.8.0
```

It works as normal
Please check this one. Thank you guys in advance. 
I really appreciate your work!

**Comment by caarlos0** [comment]
should be fixed

refs https://github.com/goreleaser/goreleaser/issues/1382
