### ISSUE TITLE
Recursive globs behaviour has changed

### ISSUE THREAD

**Issue by nhooyr** [goreleaser/nfpm#256]
See https://github.com/goreleaser/nfpm/issues/232#issuecomment-728347931

> This seems to have broken recursive globs like the following:
> https://github.com/cdr/code-server/blob/1826399cd230acc1f62556a5af7bba9c25a03a25/ci/build/nfpm.yaml#L19

```yaml
./release-standalone/**/*: "/usr/lib/code-server/"
```

> Only files two levels below the top level are copied now whereas before all files were.
> Caused a regression in code-server as nfpm wouldn't include the files in `./release-standalone/*` but only `./release-standalone/*/**/*`. i.e only files in subdirectories of the top level.
> See https://github.com/cdr/code-server/issues/2310

**Comment by caarlos0** [comment]
The previous behavior was "wrong"... you can try it with `ls`. I think what you want is `./release-standalone/**`. 

`**/*` implies only files within subdirectories.

I will make this change clearer on the release notes though.

**Comment by erikgeiser** [comment]
Hm, I thought so too at first (that `**/*` implies only files with subdirectories. However, I just tested it with three files that contain their own file name. This way I can demonstrate it with `cat` which does does no special directory processing like `ls`:

```shell
$ tree
.
├── a
│   └── b
│       └── f1
├── c
│   └── f2
└── f3

3 directories, 3 files

$ cat ./**/*
cat: ./a: Is a directory
cat: ./a/b: Is a directory
f1
cat: ./c: Is a directory
f2
f3

$ echo $SHELL
/bin/zsh

$ /bin/zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

So could indeed be a bug in https://github.com/gobwas/glob that we mistook for a feature.

**Comment by erikgeiser** [comment]
They probably would match `**` to an empty string but don't collapse multiple separator characters so `./**/*` would match `.//foo` which we consider equivalent to `./foo`.

**Comment by erikgeiser** [comment]
This indeed seems to be what's happening: https://play.golang.org/p/geU9afuijny

There is also a closed issue for this (https://github.com/gobwas/glob/issues/20). It seems like gobwas thinks that the current behaviour is correct. I made a new issue though: https://github.com/gobwas/glob/issues/46

**Comment by caarlos0** [comment]
yeah, makes sense @erikgeiser 🤔

**Comment by caarlos0** [comment]
Maybe we could hack around it and replace `**/*` with `**` only? 🤔 
No idea about the side effects of this though

**Comment by nhooyr** [comment]
Ah, I thought I tried `**` at some point and `nfpm` didn't see any files but it must have been PEBCAK.

I'll switch to that and upgrade us back.

**Comment by caarlos0** [comment]
> PEBCAK

TIL: PEBCAK 🤣

**Comment by erikgeiser** [comment]
I'm not sure any solution is right. There seem to be so many glob variants that behave differently in these exact cases. This behavior is also configurable in many shells. We probably just have to decide on a behavior we like.

Just hacking around on the pattern before compiling does not seem like a good long term solution through.

**Comment by caarlos0** [comment]
Maybe forking is a good workaround for now?

**Comment by erikgeiser** [comment]
First we need to decide what we'll do exactly. We can't really rely on shell behaviour because shell globbing behaviour is also configurable in most shells.

My `zsh` for example also treats bare `**` at the end differently than we do now:

```zsh
$ tree
.
├── a
│   └── b
│       └── f1
├── c
│   └── f2
└── f3

3 directories, 3 files
$ cat ./**
cat: ./a: Is a directory
cat: ./c: Is a directory
f3
```

To fix this issue here (`/**/*`) we could probably replace `/**/` in the AST with `{/**/,/}`. However, we will have to decide how we move forward with this if `gobwas/glob` does not want these changes. Do we continue our fork?

**Comment by caarlos0** [comment]
> Do we continue our fork?

I would say if they don't want the changes back, either that or leave as-is. So far only this issue was opened about this behavior change, so I would say its probably not too bad to leave as-is....

**Comment by djgilcrease** [comment]
You can now add directories (as long as some files exist in a nested directory) without needing globbing https://github.com/goreleaser/nfpm/blob/master/files/files_test.go#L71
```yaml
contents:
- src: testdata/deep-paths/
  dst: /bla
```
