### ISSUE TITLE
Build "source" packages that are suitable to submit to upstream projects

### ISSUE THREAD

**Issue by dexterp** [goreleaser/nfpm#275]
**Problem Definition**

To contribute to upstream projects such as Fedora, source packages are required. E.G. .spec/*.srpm files. Goreleaser only builds binaries and doesn't seem to create any source package artifacts.

**Requested Feature**
Add feature to build Source packaging for .spec/*.srpm and perhaps other source package types.

**Comment by djgilcrease** [comment]
I think you could build your own `srpm` but you would need to ensure that you kept the spec file in sync manually. I am not 100% sure on this though since I generally do not need to deal with `srpm`s.

**Comment by erikgeiser** [comment]
Maybe I don't understand this issue correctly, but isn't the whole point of `nfpm` to not have to deal with rpm specs when building packages?

**Comment by caarlos0** [comment]
Yeah, I also think we shouldn't do this.

**Comment by caarlos0** [comment]
Closing as wont fix. Thanks everyone 🙏
