### ISSUE TITLE
Missing binaries for v2.2.3

### ISSUE THREAD

**Issue by ldez** [goreleaser/nfpm#284]
The binaries are missing in the GitHub release https://github.com/goreleaser/nfpm/releases/tag/v2.2.3 because of the failure of the CI: https://github.com/goreleaser/nfpm/runs/1743472363?check_suite_focus=true

**Comment by caarlos0** [comment]
cc/ @djgilcrease 

seems like something changed in the alpine image (we are using latest). Will release from my local machine, but we'll need to check what's wrong 🤔

**Comment by caarlos0** [comment]
Release published.

**Comment by ldez** [comment]
Thank you :+1:

**Comment by djgilcrease** [comment]
So looking into this a little it looks like the original implementation was planning on having the hash data added https://github.com/goreleaser/nfpm/pull/126/files#diff-f38b522f733bebd63d1f3ec3bd91ce7643f50b81344004998457b378821c4e86R139 but never got around to getting it to work.
I am looking into this and what the actual format should be

**Comment by djgilcrease** [comment]
In alpine v3.13 they changed the warning about needing embedded checksums to an error.

I am having a hard time figuring out how to store this info properly as I cannot find it documented anywhere. @tcurdt or @bhamail Do either of you know how I would go about embedding the checksums so we do not have any errors on 3.13 of alpine?
