### ISSUE TITLE
Dumb question; how to add custom deb package ?

### ISSUE THREAD

**Issue by lucmichalski** [goreleaser/nfpm#309]
Hi guys,

Hope you are all well !

I would like to create a deb package but it has the following dependency:

```sh
apt-key adv --fetch-keys 'http://repo.manticoresearch.com/GPG-KEY-manticore'
wget https://repo.manticoresearch.com/manticore-repo.noarch.deb
dpkg -i manticore-repo.noarch.deb
apt update
apt install -y manticore
```

How can I can configure it to work with nfpm/goreleaser ?

Thanks for any insights or inputs on that question.

Cheers,
Luc Michalski

**Comment by caarlos0** [comment]
I think you'll need to put `manticore` as a dependency as per docs, but there is no way to say that it needs to come from that specific repo (not even in the deb spec AFAIK).

You could put a pre/post-install script that does that, but its a bit shady IMHO.
