### ISSUE TITLE
Install script doesn't fetch arm64 builds

### ISSUE THREAD

**Issue by oxy** [goreleaser/nfpm#314]
When running `curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh` on an arm64 CI instance, we got an error of:
`crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/goreleaser/nfpm/issues/new`

There are arm64 builds that are published in https://github.com/goreleaser/nfpm/releases/ - but the script cannot pull them down. We currently include a modified version of the script in our CI to pull the arm64 binary, but would appreciate if this can be patched!

**Comment by caarlos0** [comment]
This shell script is actually something we need to deprecate... it comes from https://github.com/goreleaser/godownloader , which is basically abandoned. 

Maybe we create our own in another url, not sure yet. For now, will remove it from the docs. Thanks

**Comment by oxy** [comment]
I think I can rewrite the shell script and send a PR - to which repository do I send a pull request to?

**Comment by caarlos0** [comment]
hmm, probably somewhere around [here](https://github.com/goreleaser/nfpm/tree/master/www/docs/static)

**Comment by hellt** [comment]
so it is not recommended to use that install script anymore?

**Comment by caarlos0** [comment]
> so it is not recommended to use that install script anymore?

yes, please use the other methods....

will close this issue. Thanks for reporting it though :)
