### ISSUE TITLE
nfpm RPMs cause rpm2cpio to silently error

### ISSUE THREAD

**Issue by mharvey-jt** [goreleaser/nfpm#341]
Hello,

I've found that RPMs generated by `nfpm`  can be successfully unpacked by `rpm2cpio`, but that tool silently errors with a non-zero exit code. Steps to repo:

```
$go install github.com/goreleaser/nfpm/cmd/nfpm@latest
$ echo '
name: "foo"
arch: "amd64"
platform: "linux"
version: "v1.0.0"
section: "default"
priority: "extra"
files:
  /etc/redhat-release: "/etc/redhat-release"
' > nfpm.yaml

$ nfpm pkg -p rpm -f nfpm.yaml
$ rpm2cpio foo-1.0.0.x86_64.rpm   > /dev/null
$ echo $?
1
```

Expectation is that `rpm2cpio` exits with 0. Confirmed that this is so with a similar RPM built with `fpm`

This occurs with the RHEL7 distro rpm and also upstream latest 4.16.1.3.

The proximal source of the error in `rpm2cpio.c` is that the payload size as determined from the RPM header does not match the actual size as returned from `ufdCopy()`

**Comment by mharvey-jt** [comment]
This is an issue in https://github.com/google/rpmpack, so will close this and move it there.

**Comment by caarlos0** [comment]
did you open an issue there as well so we can keep track?

**Comment by caarlos0** [comment]
oh, this one I assume https://github.com/google/rpmpack/issues/60
