### ISSUE TITLE
XZ-compressed Debian packages

### ISSUE THREAD

**Issue by Urethramancer** [goreleaser/nfpm#361]
I was reading over the Debian repository format, which lead to me looking into their current package formats and discovered that they now seem to require XZ support. Inspecting random packages in official Debian repos, I found the .deb  and the data.tar inside are both XZ-compressed, so it looks like they want this to be the default now.

There's already some support for creating .tar.xz archives in GoReleaser, so it's not a huge leap to also apply it to Debian packages. Making it default is probably not going to be problematic, but having the option to support old clients which only read Gzip is of course useful.

**Comment by erikgeiser** [comment]
Good point, I'll look into it. If Debian now always uses `XZ` I think it should definitely be the default for `nfpm`, too. I'll even go as far as to say that if all Debian versions that **don't** support `XZ` are EOL we could just replace the algorithm such that we don't need to introduce another configuration option. @caarlos0 what do you think, is this too radical?

**Comment by erikgeiser** [comment]
One downside of `XZ` is that we'll have to use a 350 star library instead of the standard library and it could very well make building packages slower. So we should better discuss this change thoroughly before moving forward. Maybe you'll also want to have a word in this @djgilcrease.

**Comment by caarlos0** [comment]
> @caarlos0 what do you think, is this too radical?

yeah, I think its ok...



> One downside of `XZ` is that we'll have to use a 350 star library instead of the standard library and it could very well make building packages slower. So we should better discuss this change thoroughly before moving forward. Maybe you'll also want to have a word in this @djgilcrease.

yeah, goreleaser already uses that lib, but its optional (if you choose to use tar.xz as a packaging option). The xz lib seems pretty stable fwiw...

**Comment by djgilcrease** [comment]
sounds good to me
