### ISSUE TITLE
Add -a/--arch override for nfpm package

### ISSUE THREAD

**Issue by codefromthecrypt** [goreleaser/nfpm#362]
Unless I'm missing something, we have to externally rewrite nfpm.yaml in order to do multi-platform builds, because there's no way to override the `arch:` key either by ENV convention or CLI flag. It would seem handier to do this vs have to create temporary files, right?

**Comment by codefromthecrypt** [comment]
suppose version would also be handy to override as opposed to using sed or envsubst

**Comment by djgilcrease** [comment]
Version, and arch will both expand env vars already. It looks like we need to update the docs to show that.
