### ISSUE TITLE
[deb] "arm" mistakenly converted to armhf

### ISSUE THREAD

**Issue by TechplexEngineer** [goreleaser/nfpm#367]
It seems that nfpm assumes `arm` means `armhf` [see here](https://github.com/goreleaser/nfpm/blob/master/deb/deb.go#L39). 

I don't see a way to override this behavior.

I'd be happy to send a pull request but I'm not sure what the best strategy should be to allow users to customize the behavior. Thoughts?

Per the [Debian Policy Documentation](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s-arch-spec) the `dpkg-architecture` command will list valid architectures

Here is the output from my debian machine:
```
$ dpkg-architecture -L | grep arm
<snip>
armhf
armel
arm64ilp32
armeb
arm
arm64
<snip>
```

**Comment by erikgeiser** [comment]
Currently the following values are mapped: `arm->armhf`, `arm5->armel`, `arm6->armhf`, `arm7->armhf`.
As far as I know these arch mappings were introduce to keep a consistent nomenclature between package formats. I still think this consistency is necessary.

To solve this issue, I would propose the fields `Deb.DebArch`, `RPM.RPMArch` and `Apk.ApkArch` that override `Info.Arch` without any mappings. The redundant prefix is meant to signal that it does **not** work like `Info.Arch` but rather directly overrides it without a mapping (following the respective distro's arch naming conventions).

**Comment by caarlos0** [comment]
I agree @erikgeiser...

**Comment by erikgeiser** [comment]
See #396.
