### ISSUE TITLE
debian-revision for deb packages must be the final part of the version string

### ISSUE THREAD

**Issue by kpenfound** [goreleaser/nfpm#369]
## Issue

Similar to https://github.com/goreleaser/nfpm/issues/131, the prerelease value following the release value for deb packages seems to be a bug. I believe release corresponds to debian-revision, mentioned here: https://www.man7.org/linux/man-pages/man7/deb-version.7.html

For example:
```bash
% dpkg --compare-versions 1.2.3 gt 1.2.3~beta
% echo $?
0
% dpkg --compare-versions 1.2.3 gt 1.2.3-2~beta
% echo $?
1
```
The `beta` prerelease flag should apply to the upstream version, and any package revisions with prerelease should still be treated as less than the non-prerelease version.

## Proposal
Swap the ordering here: https://github.com/goreleaser/nfpm/blob/master/deb/deb.go#L64-L74
The release should also go after `VersionMetadata` if it is indeed the debian-revision.

I'm happy to put up a PR for this, just wanted to start a discussion first to make sure I was thinking about this correctly.

**Comment by caarlos0** [comment]
I think if this is the correct way, should be fine to switch... happy to review a pr
