### ISSUE TITLE
go install fails due to replace in go.mod

### ISSUE THREAD

**Issue by WeirdBob** [goreleaser/nfpm#384]
Hi,

with versions 2.7.0 and 2.7.1, go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest will fail with the following message:

> go install: github.com/goreleaser/nfpm/v2/cmd/nfpm@latest (in github.com/goreleaser/nfpm/v2@v2.7.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

it is because of the replace directive which appeared in go.mod starting with v2.7.0:

> replace github.com/sassoftware/go-rpmutils => github.com/caarlos0/go-rpmutils v0.2.1-0.20211012234905-ebb3fe8a5fce

**Comment by caarlos0** [comment]
thanks!
