### ISSUE TITLE
Missing test `epoch`

### ISSUE THREAD

**Issue by 4censord** [goreleaser/nfpm#423]
We seem to be missing a testcase where the `epoch` field is set.

**Comment by erikgeiser** [comment]
This is tested in `TestRPM`, `TestDebEpoch` but not in for the `apk` packager. Honestly. the `apk` packager is missing a lot of tests to achieve testing parity with `deb` and `rpm`.

**Comment by 4censord** [comment]
Oh, i see. I had only looked at the acceptance tests.

**Comment by erikgeiser** [comment]
So we'd need an epoch unit test for the `apk` packager and we should extend `core.complex.yaml` to include the epoch and test for it in the Dockerfiles.

**Comment by 4censord** [comment]
should that be two seperate pull requests or one combined one?

**Comment by erikgeiser** [comment]
That can both be done in a single PR.

**Comment by caarlos0** [comment]
closing as stale
