### ISSUE TITLE
handle symlinks correctly when doing dir copy

### ISSUE THREAD

**Issue by luogni** [goreleaser/nfpm#428]
Hi, I'm using nfpm to create deb packages from a full directory with lots of files and libraries (.so files).

```
contents:
  - src: /opt/gstreamer
    dst: /opt/gstreamer
```

Normal files are copied correctly but symlinks are transformed to normal files (dpkg -c file.deb):
```
-rwxr-xr-x root/root    121152 2021-12-17 16:06 ./opt/gstreamer/lib/libswresample.so
-rwxr-xr-x root/root    121152 2021-12-17 16:06 ./opt/gstreamer/lib/libswresample.so.3
-rwxr-xr-x root/root    121152 2021-12-17 16:06 ./opt/gstreamer/lib/libswresample.so.3.9.100
```
.so and .so.3 files should be symlinks. I can't specify every single symlink because there are tons of them.

**Comment by erikgeiser** [comment]
Take a look at https://nfpm.goreleaser.com/configuration/.

Symlinks are a dedicated content type where `dst` specifies the location of the link and `src` specifies the file where the symlink points to.
