### ISSUE TITLE
Provide files as tgz

### ISSUE THREAD

**Issue by tcurdt** [goreleaser/nfpm#43]
It seems like right now there is no way to specify a full tgz for the files that should go into the package. And there is no way to specify the ownership and permissions in detail (that I see).

Would be great if one could provide a complete tgz as the data section of package.

**Comment by tcurdt** [comment]
That sounds very sceptical :) May I ask why?
How do you setup permissions of the files included in the package at the moment instead?

**Comment by caarlos0** [comment]
sorry, didn't meant to sound very skeptical haha 

right now, as far as I remember, it uses whatever permissions the files already have, although I agree that's not ideal.

I use it only on goreleaser itself, and for what goreleaser supports that was never a problem, but to support "power users" I agree there must be a better way...

**Comment by tcurdt** [comment]
If you have any thoughts on how you this could or should be added best I am all ears.
Maybe I can then work on a PR.

**Comment by jarondl** [comment]
Now with #79 by @djgilcrease , nfpm can perhaps offer using `rpmpack.FromTar` as an additional input method.

**Comment by djgilcrease** [comment]
I would say add a `FilesTar string` to [Overridables](https://github.com/goreleaser/nfpm/blob/master/nfpm.go#L136) make sure it is mutually exclusive with the `Files []string` then update [createDataTarGz](https://github.com/goreleaser/nfpm/blob/master/deb/deb.go#L91) to use the passed in `FilesTar` if set && update [Package](https://github.com/goreleaser/nfpm/blob/master/rpm/rpm.go#L45) to use [FromTar](https://github.com/google/rpmpack/blob/master/tar.go#L28) if `FilesTar` is set

**Comment by mig4** [comment]
Yeah, I just wanted to confirm the expectation was that this would be an additional option in the config file, instead of a CLI arg for example. As for in addition/instead, whatever makes most sense. I'll give it a spin and propose something and we can discuss the details there sure.

Many thanks for the pointers @djgilcrease :grin:

**Comment by caarlos0** [comment]
closing due to lack of interest from the community

**Comment by tcurdt** [comment]
@caarlos0 is there any other way to specify ownership and permissions of files inside the package by now?

**Comment by caarlos0** [comment]
yes, https://nfpm.goreleaser.com/configuration/?h=file_info#reference
