### ISSUE TITLE
ENV variables in files paths

### ISSUE THREAD

**Issue by Felixoid** [goreleaser/nfpm#449]
Hello, I've asked the question in [slack](https://gophers.slack.com/archives/C3T1JU24B/p1644224859381649) but had no answers.

I am adding `nfpm` in the project currently, and have found that ENV vars aren't exposed in the files list. It's not a big issue, but something that would a bit help us during the build. Would you consider the feature to add in case of PR or it doesn't make sense to you?

Example: I put all configs in a separate directory `packages` and launch `nfpm ..` from a root repo dir. Then `./` in the file list is exposed to `$PWD`, but I'd rather like to have it in packages. Exposing ENV to an absolute path would solve it easily.

**Comment by djgilcrease** [comment]
Expanding environment vars in file path is problematic as the env var indicators are valid file name characters. I would prefer we not support this as deciding when to use our not use substation would be an issue, better for the user to use `envsubst` or other variable replacement system as a pre step in their build process to generate a realized config file.

**Comment by caarlos0** [comment]
agreed with @djgilcrease.

closing

**Comment by Felixoid** [comment]
Ok, thank you for your feedback
