### ISSUE TITLE
Invalid docker images for v2.12

### ISSUE THREAD

**Issue by jability** [goreleaser/nfpm#452]
### What happened?

Hello,
Since v2.12.x, the nfpm binary cannot be found inside the docker images.

### How can we reproduce this?

```bash
$ docker container run --rm goreleaser/nfpm:v2.12.1
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/bin/nfpm": stat /usr/local/bin/nfpm: no such file or directory: unknown.
```

### nfpm version

```bash
v2.12.x
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ah, thanks, pushing a fix!
