### ISSUE TITLE
Add RPM file digest options (sha256)

### ISSUE THREAD

**Issue by ngharo** [goreleaser/nfpm#464]
### Is your feature request related to a problem? Please describe.

Packages produced by nfpm do not install on Red Hat 8 when FIPS mode is enabled.

MD5 digests are not FIPS compliant. Adding file digest options for RPM packaging can allow consumers of this project to produce FIPS compliance RPM packages.

The equivalent flag for this feature in fpm is `--rpm-digest`.

Example issue from Grafana project experiencing this issue
https://github.com/grafana/grafana/issues/41036

### Describe the solution you'd like

Ability to specify RPM file digest algorithm, defaulted to sha256.

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
are you sure that that's the issue? 

we use rpmpack underneath, and it does set the digest to sha256 -> https://github.com/google/rpmpack/blob/master/rpm.go#L394-L395

**Comment by ngharo** [comment]
Thanks and I think you're right, the problem is elsewhere.

Closing this out.

**Comment by caarlos0** [comment]
cool, please share what you find out :D
