### ISSUE TITLE
Add support for arbitrary .deb control file fields

### ISSUE THREAD

**Issue by atheriel** [goreleaser/nfpm#490]
### Is your feature request related to a problem? Please describe.

Debian control files [have a number of optional fields](https://man7.org/linux/man-pages/man5/deb-control.5.html) -- including "Bugs" and "Tags" -- that are used by many existing packages. The original `fpm` [supports adding arbitrary fields to Debian control files with the --deb-field flag](https://fpm.readthedocs.io/en/latest/packages/deb.html?highlight=changelog#deb-specific-command-line-flags), but in my understanding it's not currently possible to do so with `nfpm`.

I'm currently trying to port some packaging code from `fpm` and `nfpm` and it seems unfortunate to give up these fields to do so.

### Describe the solution you'd like

I'd like to see support for custom Debian control fields added to `nfpm`. My imagined configuration would add a new setting under the existing `deb` section like this:

```yaml
deb:
  fields:
    - name: Bugs
      value: https://github.com/goreleaser/nfpm/issues
```

### Describe alternatives you've considered

Since these fields are optional, `nfpm` may chose not to support them. As I mentioned, I think this would be unfortunate and keep folks on `fpm` in some cases.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'd be willing to implement this if there is interest.

**Comment by caarlos0** [comment]
ah, that seems good to have indeed

**Comment by atheriel** [comment]
OK, I'll take a crack at it.
