### ISSUE TITLE
Post-remove script example seems incorrect

### ISSUE THREAD

**Issue by gregcotten** [goreleaser/nfpm#501]
### What happened?

This [example in the docs](https://github.com/goreleaser/nfpm/blob/1f50ccc8302150320552d7fe6dd9e2c15d604a1e/www/docs/tips.md#example-multi-platform-rpm--deb-post-remove-script) seems to not actually be an example of post-remove, as it references install + upgrade.

### How can we reproduce this?

View the URL

### nfpm version

```bash
n/a
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dean-Coakley** [comment]
@caarlos0 I was considering proposing a fix of just replacing the example with the contents of https://github.com/goreleaser/nfpm/blob/main/testdata/acceptance/scripts/postremove.sh

Would that be sufficient?

**Comment by djgilcrease** [comment]
yup that would work
