### ISSUE TITLE
Support IPK package format

### ISSUE THREAD

**Issue by mlois-efimob** [goreleaser/nfpm#507]
### Is your feature request related to a problem? Please describe.

Create a package for a OpenWrt or another embedded distribution that uses opkg and ipkg packages, that are debian simplified packages.

### Describe the solution you'd like

To be able to generate a ipk with as deb packaging is supported 

### Describe alternatives you've considered

Build the packages by myself.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mlois-efimob** [comment]
I think that the OpenWrt project that uses this package format has docker images already built for every release: https://openwrt.org/docs/guide-user/virtualization/docker_openwrt_image also other distributions as OpenEmbedded uses ipk as well.

**Comment by erikgeiser** [comment]
In what way do these packages actually differ from `deb` packages?

**Comment by caarlos0** [comment]
1 year, no reply, closing.... reopen/comment if needed.

**Comment by schmidtw** [comment]
I have a need for this for supporting yocto build communities.  I'm exploring what it would take to write this.

**Comment by schmidtw** [comment]
@erikgeiser there are quite a few ways these differ from deb packages.  There isn't any formal documentation from what I have found :disappointed: but I have been focusing on the `opkg` packaging tool code from openwrt & yocto.

Summary:
- Signing isn't done at the package level, but the "feed" or repo provider level.
- Fewer configuration options, more opinionated.
- No triggers/rules, limited scripts.
- Documentation is stripped for size.

**Comment by caarlos0** [comment]
> 1 year, no reply, closing.... reopen/comment if needed.

didn't actually close it.. closing it now.

**Comment by schmidtw** [comment]
@caarlos0 I'm about a week away from having a PR submitted to add ipk support if you'll still take it.  I'm working out the acceptance tests.

**Comment by caarlos0** [comment]
Ah, yeah sounds good!

**Comment by schmidtw** [comment]
I'm sorry - I didn't realize my local branch pushes were creating all these comments ... :disappointed:

**Comment by caarlos0** [comment]
this is done
