### ISSUE TITLE
Support dpkg-sig style package signing for debian packages

### ISSUE THREAD

**Issue by SasSwart** [goreleaser/nfpm#509]
### Is your feature request related to a problem? Please describe.

debsign is a PITA, as per issue #212.

I'd like to be able to sign packages using dpkg-sig, because they are easier to verify.

### Describe the solution you'd like

Please review my PR #508, where I implement dpkg-sig style signing.

### Describe alternatives you've considered

I considered configuring debsign, but it was easier to implement dpkg-sig package signing than to figure out what they want their xml and specific subdirectories to look like.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
done in #515 and #508
