### ISSUE TITLE
Generate macOS installer (`*.pkg`)

### ISSUE THREAD

**Issue by skyzyx** [goreleaser/nfpm#535]
### Is your feature request related to a problem? Please describe.

NFPM is a handy tool for generating packages. Currently, it appears that only Linux is supported, but it'd be awesome if we could create macOS installer packages as well.

### Describe the solution you'd like

Adapted from: https://apple.stackexchange.com/questions/176653/mac-package-installer-installs-the-folder-contents-in-applications-instead-of

```bash
pkgbuild --analyze --root ./dist/macos-universal_darwin_all/ MyGoCLIApp.plist

pkgbuild --root ./dist/macos-universal_darwin_all/ --component-plist MyGoCLIApp.plist --identifier com.net.org.biz --version 0 --install-location /usr/local/bin MyGoCLIApp.pkg
```

…But using NFPM.

### Describe alternatives you've considered

Continuing to add commands by hand.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
the idea of nfpm is to package things using go code only, not calling binaries that might or not be available in some platforms.

afaik its not possible to do so for dmg files, so, closing this.
