### ISSUE TITLE
Generate macOS disk image (`*.dmg`)

### ISSUE THREAD

**Issue by skyzyx** [goreleaser/nfpm#536]
### Is your feature request related to a problem? Please describe.

NFPM is a handy tool for generating packages. Currently, it appears that only Linux is supported, but it'd be awesome if we could create macOS installer packages and ship them in disk images as well.

### Describe the solution you'd like

```bash
rm -Rf temp.dmg
mkdir -p temp.dmg
mv MyGoCLIApp.pkg ./temp.dmg

# https://ss64.com/osx/hdiutil.html
hdiutil create \
  -srcfolder ./temp.dmg/ \
  -volname "My Go CLI App" \
  -fs HFS+ \
  -fsargs "-c c=64,a=16,e=16" \
  -format UDRW \
  -size $(( $(du ./temp.dmg/MyGoCLIApp.pkg 2>&1 | cut -d$'\t' -f1) * 1536)) \
  MyGoCLIApp.dmg
```

…But using NFPM.

Notes:

* `du` returns values in _true_ kilobytes (_bytes_ * 1000).
* The DMG needs to be bigger than the file(s). I chose `1024` (to go from kB → MB) × `1.5`. `1.0` was too small and triggered obscure error messages.

### Describe alternatives you've considered

Continuing to add commands by hand.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
the idea of nfpm is to package things using go code only, not calling binaries that might or not be available in some platforms.

afaik its not possible to do so for dmg files, so, closing this.
