### ISSUE TITLE
Problem with https://repo.goreleaser.com

### ISSUE THREAD

**Issue by benz0li** [goreleaser/nfpm#540]
### What happened?

```
Err:6 https://repo.goreleaser.com/apt  InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 34.231.67.215 443]
Reading package lists...
W: Failed to fetch https://repo.goreleaser.com/apt/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 34.231.67.215 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### How can we reproduce this?

According to https://nfpm.goreleaser.com/install/#apt:

```bash
echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
sudo apt update
sudo apt install nfpm
```

### nfpm version

```bash
not relevant
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
is it a docker container? If so, make sure to install ca-certificates, it usually is not installed in containers

other than that, I don't have many ideas, its working normally in all the machines I tested...

**Comment by benz0li** [comment]
> is it a docker container? If so, make sure to install ca-certificates, it usually is not installed in containers

Yes. Latest versions of `ca-sertificates` and `openssl` installed.

> other than that, I don't have many ideas, its working normally in all the machines I tested...

Just now it started working again. Page https://repo.goreleaser.com was down or misconfigured before.

**Comment by benz0li** [comment]
Never had a problem with https://repo.goreleaser.com before though.

👍

**Comment by caarlos0** [comment]
hmm maybe some issue in fury (which serves the repo)
