### ISSUE TITLE
Add support for copyright metadata in debian packages

### ISSUE THREAD

**Issue by barthisrael** [goreleaser/nfpm#561]
### Is your feature request related to a problem? Please describe.

It is a feature request. I would like to be able to add the `debian/copyright` metadata into the `deb` package through `nFPM`. This is how that file usually looks like:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Files: *
License: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
laborum.
X-License-Url: https://www.mywebsite.com/mylicense
Sources: https://www.mywebsite.com/mytool
Copyright: mycopyright
Upstream-Name: mypackage
```

### Describe the solution you'd like

Some way of specifying through the `yml` file that the copyright metadata should be present in the `deb` package.

### Describe alternatives you've considered

So far we are working around by:

- generating the packages through `nFPM`
- unpacking
- including the `debian/copyright`
- repacking

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barthisrael** [comment]
I forgot to mention it earlier here, but we worked around this issue by creating the copyright file and then specifying the following in our nFPM configuration file:

```
- src: build/copyright
  dst: /usr/share/doc/<product_name>/copyright
  packager: deb
```

**Comment by caarlos0** [comment]
I think that's a good enough alternative, might be worth adding it to our docs though
