### ISSUE TITLE
archlinux packager doesn't use `prerelease` option

### ISSUE THREAD

**Issue by j-tai** [goreleaser/nfpm#577]
### What happened?

The `prerelease` option in the config is completely unused by the `archlinux` packager. I expected it to show up in the version number, like it does with the `deb` packager.

### How can we reproduce this?

nfpm.yaml:

```yml
name: foo
version: 1.2.3
prerelease: beta1
maintainer: asdf
arch: amd64
contents: []
```

run:

```console
$ nfpm package -p archlinux
using archlinux packager...
created package: foo-1.2.3-1-x86_64.pkg.tar.zst
$ tar xf foo-1.2.3-1-x86_64.pkg.tar.zst .PKGINFO
$ cat .PKGINFO 
# Generated by nfpm
pkgname = foo
builddate = 1668647593
packager = Unknown Packager
size = 0
pkgbase = foo
pkgver = 1.2.3-1
pkgdesc = no description given
arch = x86_64
```

### nfpm version

```bash
nfpm version nfpm version 2.22.0
commit: 5c3cc38943f1743bcaeb422c2dc65555fc9b12a1
built at: 2022-11-12T03:50:16Z
built by: goreleaser
module version: v2.22.0, checksum: h1:TC6tuxxFq0hL0WapI63+CkLMbcsYRbR7kAnLkRYAEbo=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, good point, according to [this](https://wiki.archlinux.org/title/PKGBUILD#pkgver), we should just append it to the `pkgver`.

Will work on a PR

**Comment by caarlos0** [comment]
could you check #578?
