### ISSUE TITLE
nfpm 2.25.1 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [goreleaser/nfpm#620]
### What happened?

👋 it looks like nfpm 2.25.1 release was not completed (see [this workflow run](https://github.com/goreleaser/nfpm/actions/runs/4097111546/jobs/7065245678) for details).

### How can we reproduce this?

N/A

### nfpm version

```bash
supposedly 2.5.1
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

relates to https://github.com/Homebrew/homebrew-core/pull/122354

**Comment by caarlos0** [comment]
oh, thanks for noticing, running it locally and cutting .2 from main
