### ISSUE TITLE
schema.json file is missing

### ISSUE THREAD

**Issue by gesquive** [goreleaser/nfpm#653]
### What happened?

followed the [documentation](https://nfpm.goreleaser.com/configuration/#json-schema) and tried to use the jsonschema file at `https://nfpm.goreleaser.com/schema.json`. That URL just returns a 404.

### How can we reproduce this?

Use curl: `curl -I https://nfpm.goreleaser.com/schema.json`

### nfpm version

```bash
v2.28.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gesquive** [comment]
I took a quick look at the documentation build process, and it looks like the correct URL is `https://nfpm.goreleaser.com/static/schema.json`. I'm not sure how to move that file into the right location for it to be at `https://nfpm.goreleaser.com/schema.json`

**Comment by caarlos0** [comment]
oh, it was always located in /static/schema.json, I think the bug is in the docs, pointing out to the wrong URL...
