### ISSUE TITLE
nFPM doesn't seems support includes

### ISSUE THREAD

**Issue by Libaud** [goreleaser/nfpm#662]
### Is your feature request related to a problem? Please describe.

nFPM is a very good tool, but doesn't seems support includes files with YAML syntax. It will be very useful for multiples packages with the same parameters.

### Describe the solution you'd like

YAML include file support syntax.

### Describe alternatives you've considered

Or another way to include files in cascade for params the nfpm packaging project configuration file.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

For example a project with X86 and X64 architecture, there's two package that correspond to these. And there's two nfpm configuration file. But the same parameters base.

**Comment by caarlos0** [comment]
you can use environment variables in many fields, if I recall correctly, arch is one of them.

You can also pipe the file through some template engine before handling it to nfpm.

All that being said, ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
