### ISSUE TITLE
Error: unknown field ______ in struct literal of type "github.com/goreleaser/nfpm/v2".Overridables

### ISSUE THREAD

**Issue by pranav-new-relic** [goreleaser/nfpm#665]
### What happened?

Hi, not sure if this is a bug or I'm missing something in my configuration - but the following is the scenario.

I currently work on a Terraform (Go-based) open source repository, where we currently use nfpm version 2.15.0 (as you may see in this line of [go.mod](https://github.com/newrelic/terraform-provider-newrelic/blob/main/tools/go.mod#L160)).

We would like to update this to v2.29.0, to do which an automated PR was created via GitHub to update the version to 2.29.0. Tests running on the PR show the following compile error when 2.29.0 is used (you can also find at the bottom in [this link](https://github.com/newrelic/terraform-provider-newrelic/actions/runs/5112782452)).

<img width="855" alt="image" src="https://github.com/goreleaser/nfpm/assets/127438038/766dce6c-7d40-4e04-8877-3286e09910ba">

To validate if this is the case when I try doing this locally too, I first ran the command ` go get -u "github.com/goreleaser/nfpm/v2@v2.29.0"`, after which `go.mod` got updated with v2.29.0. After this, I ran `make compile` on the project, and see the same error.

<img width="1629" alt="image" src="https://github.com/goreleaser/nfpm/assets/127438038/af8b91ec-8b2b-419e-803e-c7893214bf3b">

When I revert the changes made to `go.mod` (i.e. revert the version to 2.15.0), I don't see the error.

Not sure if this is a bug - I'm sure I must be missing something (my suspicion is this must be something with versions of other modules of goreleaser that are inaccurate or are causing this dependency issue). Any inputs would be appreciated, thank you!

### How can we reproduce this?

Cannot be reproduced on your end

### nfpm version

```bash
Probably cannot be specified as it is in a Go dependency
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
it seems you are using a very old version of goreleaser, and trying to use it with a new version of nfpm.

upgrading goreleaser instead should work.
