### ISSUE TITLE
RFE: ability to exclude files

### ISSUE THREAD

**Issue by scop** [goreleaser/nfpm#670]
### Is your feature request related to a problem? Please describe.

When packaging software using goreleaser nfpms, goreleaser automatically includes all binaries in all packages, apparently with no way to prevent that. In various cases for various reasons it would be beneficial to split the set of produced binaries over multiple packages.

One such example: https://github.com/aakso/ssh-inscribe currently produces separate client and server packages (using fpm), and the split makes perfect sense, as it's very rare to require both the client and server on a single box. I'm planning to migrate it over to goreleaser+nfpm, but while I can produce several nfpm packages from a build, they all contain all (well both) binaries.

### Describe the solution you'd like

If nfpm had the ability to _exclude_ files from a package that would otherwise end up in it, I think that would solve the problem quite nicely. One could just mark the undesired binary/binaries that goreleaser automatically puts there as excluded, and they would not end up in the corresponding packages. Another use case would be the ability to exclude specific files that would otherwise be included when using a glob or a tree content entry.

I suppose this could be implemented for example with `contents` entries without a `src` and a type marking exclusion:
```yaml
contents:
  - dst: /file/to/exclude # globs too
    type: exclude
```
...or a separate top level `exclude-contents` config, contaning an array of files/globs to exclude.

### Describe alternatives you've considered

Building with goreleaser, packaging with nfpm outside of goreleaser, using data from artifacts.json, each "sub"package using separate nfpm config of its own.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you mean that your config has multiple builds, and the packages generated have the binaries from both builds?

if so, the `nfpms` config has a `builds` array which you can use to filter by build id

**Comment by scop** [comment]
Dang, and sweet, I completely missed that. That covers my use case, please feel free to close this RFE unless you see some other value in it. Thanks!
