### ISSUE TITLE
AppImage support?

### ISSUE THREAD

**Issue by patryk4815** [goreleaser/nfpm#694]
### Is your feature request related to a problem? Please describe.

Do you think it is possible to add AppImage support?
Or it is out of scope for this project.

### Describe the solution you'd like

building AppImage package

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kovmir** [comment]
`Go` produces statically linked binaries, what would you need an `AppImage` for?

**Comment by patryk4815** [comment]
@kovmir You still can 'package' non golang binary Or cgo binary.

**Comment by kovmir** [comment]
I am not sure I understand your previous message.

I am not saying it is impossible to make an `AppImage`, I am asking what you would need it for. You can run a go binary just like you would run an `AppImage` with all the dependencies bundled in.

**Comment by patryk4815** [comment]
@kovmir Im bundling C++ binaries

**Comment by caarlos0** [comment]
Closing due to lack of community interest on this.
