### ISSUE TITLE
Support env var expansion for `contents.src`

### ISSUE THREAD

**Issue by AlekSi** [goreleaser/nfpm#719]
### Is your feature request related to a problem? Please describe.

I have a directory structure produced by Docker/BuildKit multi-platform build:
```
tmp/build/
├── linux_amd64
│   └── my-bin
└── linux_arm64
    └── my-bin
```

I want to be able to use the single `nfpm.yml` configuration file for both architectures. Unfortunately, it is not possible to use environment variable expansion in `contents.src`.

### Describe the solution you'd like

```yaml
arch: ${ARCH}
contents:
  - src: tmp/build/linux_${ARCH}/my-bin
    dst: /usr/bin/my-bin
```

### Describe alternatives you've considered

Using multiple `nfpm.yml` files. Using external templates. I would like to avoid both those alternatives.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I should be able to contribute that change if that's something you want to have.

**Comment by AlekSi** [comment]
Thank you!

**Comment by AlekSi** [comment]
It would be nice to have it released :)

**Comment by caarlos0** [comment]
released, sorry for the delay

**Comment by Felixoid** [comment]
I think it's the same as in https://github.com/goreleaser/nfpm/issues/449
