### ISSUE TITLE
Configuration Docs tells us not to use v prefix but it is included by nfpm init

### ISSUE THREAD

**Issue by elibroftw** [goreleaser/nfpm#730]
### What happened?

`nfpm init` created a nfpm.yaml file but the version starts with a v even though the https://nfpm.goreleaser.com/configuration/ docs tells us not to.

### How can we reproduce this?

install nfpm on macosx using brew install nfpm, run nfpm init, open nfpm.yaml

### nfpm version

```bash
GitVersion:    v2.34.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.21.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
good catch!
