### ISSUE TITLE
no packager registered for the format archinux

### ISSUE THREAD

**Issue by elibroftw** [goreleaser/nfpm#731]
### Is your feature request related to a problem? Please describe.

yes, no instructions on how to package for arch linux on Debian based system. Or how to use nfpm on github actions in the tips section to package for all three packagers. 

### Describe the solution you'd like

Docs that informs users how to package for archlinux on Debian-based systems or from github actions or to explicitly tell us that even though linux is open source and is all about freedom, we need arch linux to build for arch linux?

### Describe alternatives you've considered

Using docker containers to do it.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
on the issue title at least you have a typo, `archinux` -> `archlinux` (missing the `l`)

>  we need arch linux to build for arch linux?

you don't. 

> Docs that informs users how to package for archlinux on Debian-based systems or from github actions 

its the same usage as its outside actions, which is already documented.
