### ISSUE TITLE
`mtime` is not used from config

### ISSUE THREAD

**Issue by keliramu** [goreleaser/nfpm#750]
### What happened?

After recent changes, in your code you do not copy `c.MTime` over to `info.MTime`.
Also, you do not enforce `mtime` onto `info.Content` Files.

I would expect that `mtime` from config (or from env variable) to be enforce on all timestamps.

### How can we reproduce this?

Code location: https://github.com/goreleaser/nfpm/blob/main/nfpm.go#L123
here you need to `info.MTime = c.MTime`

### nfpm version

```bash
using Dec 7 commit: 7439013fb5dc9357e84aabb36823a21c1b97e8ba
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, seems like mergo is ignoring that field (and many others??) 


will investigate
