### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by Repana-Chowdappa** [goreleaser/nfpm#801]
### Is your feature request related to a problem? Please describe.

s390x artifacts are currently not being published to the releases page.

### Describe the solution you'd like

We would like to open a PR for ppc64le support.

### Describe alternatives you've considered

s390x seems to be there already in some source files.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Hi team,
I am from the IBM Z (s390x) porting team. We would like to open a PR for s390x support so that the artifacts are published to the releases page for subsequent releases. I searched through the source files but could not find where to make this change. Can you please help?

**Comment by caarlos0** [comment]
someone from ibm opened the exact same issue for ppc64 a couple of months ago...

**Comment by Repana-Chowdappa** [comment]
@caarlos0 Yes, I saw the power(ppc64) pull request, I see there is only 1 change in` .goreleaser.yml ` and you have completed it as part of https://github.com/goreleaser/nfpm/commit/37b28fd4a368a94e4e285bdabbd3c1641f28cff4

**Comment by Repana-Chowdappa** [comment]
Please do let me know if this single change work for s390x support?

**Comment by Repana-Chowdappa** [comment]
@caarlos0 - When we will be able to get the s390x binary on https://github.com/goreleaser/nfpm/releases/download ?
