### ISSUE TITLE
Has the minimum Go version (intentionally) changed?

### ISSUE THREAD

**Issue by atc0005** [goreleaser/nfpm#820]
### What happened?

Minimum Go version changed from 1.19 to 1.22 via:

- https://github.com/goreleaser/nfpm/pull/813

This was surprising since Go 1.21 was set as the minimum Go version in this commit:

- https://github.com/goreleaser/chglog/commit/60200f14319dc2ecffbb208698213439e352af3a

I would have expected Go 1.21 to be the minimum Go version.

The contributing doc notes that Go 1.19 and newer is supported:

- https://github.com/goreleaser/nfpm/blob/main/CONTRIBUTING.md

### How can we reproduce this?

If you attempt to install nfpm via `go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.37.0` using Go 1.21 you get this error:

> `go: github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.37.0: github.com/goreleaser/nfpm/v2@v2.37.0 requires go >= 1.22 (running go 1.21.10; GOTOOLCHAIN=local)`

### nfpm version

```bash
v2.36.1 builds/installs successfully using Go 1.21
v2.37.0 fails to build

Build error:

> `go: github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.37.0: github.com/goreleaser/nfpm/v2@v2.37.0 requires go >= 1.22 (running go 1.21.10; GOTOOLCHAIN=local)`
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If the minimum Go version change is intentional then the https://github.com/goreleaser/nfpm/blob/main/CONTRIBUTING.md doc probably needs updating to reflect that, in which case the fix is to update that file instead of reverting the minimum version listed in this project's go.mod file.

**Comment by atc0005** [comment]
On a different note, many thanks for this tool!

**Comment by caarlos0** [comment]
pushed new tag with the fixes, let me know if it works as expected now.

* min go version is go1.21.
* also updated contributing.md

**Comment by atc0005** [comment]
@caarlos0 That was fast!

nfpm v2.37.1 builds without issue using Go 1.21.

Thank you!
