### ISSUE TITLE
Relative paths for src are treated as symlinks

### ISSUE THREAD

**Issue by leungster** [goreleaser/nfpm#826]
### What happened?

Given a config where `src` is a relative path to a file, nfpm forces the filetype to be a symlink. 
It appears the cause may be due to the usage of [os.Readlink in files.go](https://github.com/goreleaser/nfpm/blob/745b0f59d9cbab3cb4d0a3373e7569bec4ca1bd9/files/files.go#L433C18-L433C29) to check if the src is a symlink or not.
`os.Readlink` does not convert the input into an absolute path first and will echo back relative paths as is per [go docs](https://pkg.go.dev/os#Readlink).

I am using bazel to generate my src files and nfpm config file. Since bazel operates on relative paths, nfpm is forcing all my files to be symlinks in the output artifact.

### How can we reproduce this?

Create a nfpm config with a relative path for `src`.
```yaml
contents:
  - src: relative/path/foo
    dst: /usr/bin/foo
```

### nfpm version

```bash
v2.34.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I cannot reproduce this.

Tried writing a failing test, and it doesn't seem to happen, at least not on linux.

#833

**Comment by leungster** [comment]
Thanks for looking into this. 

I debugged this a bit more under Bazel and the file was actually a symlink. Bazel is creating symlinks under the execution path.
