### ISSUE TITLE
field rpm_arch not found in type nfpm.RPM

### ISSUE THREAD

**Issue by marcvs** [goreleaser/nfpm#872]
### What happened?

Packages build fine, except the RPM arch is "undefined"
setting in `nfpm.yml`
either
```yaml
rpm:
  rpm_arch: ia64
```
or
```yaml
rpm_arch: ia64
```
yields the error:
```
field rpm_arch not found in type nfpm.RPM
```

### How can we reproduce this?

See `nfpm.yaml` in <https://codebase.helmholtz.cloud/m-team/oidc/ssh/webssh-oidc/-/tree/add-packaging?ref_type=heads>

### nfpm version

```bash
I'm using this in a pipeline on a debian-trixie, installing your version 2.40:

`Get:1 https://repo.goreleaser.com/apt  nfpm 2.40.0`
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, bad docs, it should be

```yaml
rpm:
  arch: ia64
```
